services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27107
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - mongo